---
# Переменные для geerlingguy.pip
pip_install_packages:
  - name: docker

# Переменные для Redmine
redmine_port: 80
redmine_db_host: rc1a-o0qmnm7or1c8dglq.mdb.yandexcloud.net
redmine_db_port: 6432
redmine_db_name: redmine
redmine_db_user: redmine_user
redmine_db_password: "{{ vault_redmine_db_password | default('') }}"

# Переменные для Datadog Agent
datadog_site: "datadoghq.com"
datadog_api_key: "{{ vault_datadog_api_key | default('') }}"

# Конфигурация интеграции http_check
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: "Redmine App Check"
        url: "http://localhost:{{ redmine_port }}"
        timeout: 5
        collect_response_time: true
