[webservers]
app-1 ansible_host=51.250.85.184 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
app-2 ansible_host=62.84.117.108 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
