[webservers]
app-1 ansible_host=51.250.6.245 ansible_user=yc-user ansible_ssh_private_key_file=~/.ssh/id_ed25519
app-2 ansible_host=158.160.3.92 ansible_user=yc-user ansible_ssh_private_key_file=~/.ssh/id_ed25519
