---
- name: Подготовка серверов и деплой Redmine
  hosts: all
  become: yes
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

  roles:
    - { role: geerlingguy.pip, tags: [setup] }
    - { role: geerlingguy.docker, tags: [setup] }
    - { role: redmine, tags: [deploy] }
    - { role: datadog.datadog, tags: [monitoring], when: "'webservers' in group_names" }
