---
- name: Подготовка серверов и деплой Redmine
  hosts: all
  become: yes
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

  roles:
    - { role: geerlingguy.pip, tags: [setup] }
    - { role: geerlingguy.docker, tags: [setup] }
    - { role: redmine, tags: [deploy] }
    - { role: datadog.datadog, tags: [monitoring], when: "'webservers' in group_names" }

  post_tasks:
    - name: Configure Upmon website uptime check cron job
      ansible.builtin.cron:
        name: "Upmon heartbeat ping"
        minute: "*/5"
        job: 'curl -sf http://localhost > /dev/null || exit 1 && curl -fsS --retry 3 {{ upmon_ping_url }} > /dev/null'
      when: "'webservers' in group_names"

